on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy, push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Deploy
      run: echo "deployed"